"""Project-neutral data-source discovery and DuckDB workspace generation.

Portfolio projects describe their raw data through a small YAML manifest.  When
no manifest exists, the service discovers supported files under ``data/raw``,
infers sensible table names and relationship candidates, and creates a reusable
DuckDB setup script plus validation starters.  The generated configuration is
project-local so the same engine works for any learner project.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
import csv
import hashlib
import json
import os
from pathlib import Path
import re
import shutil
import subprocess
import sys
from typing import Any, Iterable

import yaml

from career_app.data.roadmap import PROJECT_DIRS, PROJECT_NAMES


CONFIG_VERSION = 2
CONFIG_RELATIVE = Path("config/project_sources.yaml")
LEGACY_CONFIG_RELATIVES = (Path("data/project_sources.yaml"),)
DATABASE_RELATIVE = Path("data/working/project.duckdb")
STARTER_SQL_RELATIVE = Path("sql/validation/validate_relationships.sql")
FINDINGS_RELATIVE = Path("documentation/relationship_validation.md")
LEGACY_SETUP_RELATIVES = (
    Path("sql/setup/01_register_raw_sources.sql"),
    Path("sql/setup/01_register_raw_views.sql"),
)
LEGACY_VALIDATION_RELATIVES = (
    Path("sql/validation/01_primary_key_checks.sql"),
    Path("sql/validation/02_orphan_key_checks.sql"),
    Path("sql/validation/03_join_cardinality_checks.sql"),
    Path("sql/validation/04_relationship_consistency_checks.sql"),
)
SUPPORTED_SUFFIXES = {".csv", ".parquet", ".json", ".jsonl", ".ndjson"}
MANAGED_HEADER = "Generated by Data Career Accelerator project-data workspace"
STARTER_HEADER = "DCA Portfolio SQL Starter v2"
FINDINGS_HEADER = "DCA Portfolio Findings Template v2"
MANAGED_GUIDE_START = "<!-- DCA:PROJECT-DATA:START -->"
MANAGED_GUIDE_END = "<!-- DCA:PROJECT-DATA:END -->"


@dataclass(frozen=True)
class ProjectSource:
    name: str
    path: str
    format: str
    view: str
    columns: tuple[str, ...] = ()
    primary_key: str = ""


@dataclass(frozen=True)
class ProjectRelationship:
    parent: str
    parent_key: str
    child: str
    child_key: str
    cardinality: str = "one-to-many"
    inferred: bool = True


@dataclass
class ProjectDataPlan:
    project_id: int
    project_name: str
    project_dir: Path
    schema: str = "raw"
    database_path: Path | None = None
    config_path: Path | None = None
    starter_sql_path: Path | None = None
    findings_path: Path | None = None
    workspace_path: Path | None = None
    migration_report_path: Path | None = None
    sources: list[ProjectSource] = field(default_factory=list)
    relationships: list[ProjectRelationship] = field(default_factory=list)
    database_ready: bool = False
    warnings: list[str] = field(default_factory=list)

    @property
    def source_count(self) -> int:
        return len(self.sources)

    @property
    def relationship_count(self) -> int:
        return len(self.relationships)


class ProjectDataError(ValueError):
    pass


def _project_dir(root: Path, project_id: int) -> Path:
    try:
        directory = PROJECT_DIRS[int(project_id)]
    except KeyError as exc:
        raise ProjectDataError(f"Unknown portfolio project: {project_id}") from exc
    return (Path(root) / "projects" / directory).resolve()


def _safe_relative(project_dir: Path, value: str | Path) -> Path:
    candidate = Path(value)
    if candidate.is_absolute():
        resolved = candidate.resolve()
    else:
        resolved = (project_dir / candidate).resolve()
    try:
        resolved.relative_to(project_dir)
    except ValueError as exc:
        raise ProjectDataError("Project data path leaves the project folder.") from exc
    return resolved


def _slug(value: str, fallback: str = "table") -> str:
    value = re.sub(r"[^a-zA-Z0-9_]+", "_", str(value or "")).strip("_").lower()
    value = re.sub(r"_+", "_", value)
    if value.startswith("raw_"):
        value = value[4:]
    if not value:
        value = fallback
    if value[0].isdigit():
        value = f"t_{value}"
    return value


def _singular(value: str) -> str:
    text = str(value)
    if text.endswith("ies") and len(text) > 3:
        return text[:-3] + "y"
    if text.endswith("ses") and len(text) > 3:
        return text[:-2]
    if text.endswith("s") and not text.endswith("ss") and len(text) > 1:
        return text[:-1]
    return text


def _sql_string(value: str | Path) -> str:
    return "'" + str(value).replace("\\", "/").replace("'", "''") + "'"


def _qid(value: str) -> str:
    return '"' + str(value).replace('"', '""') + '"'


def _format_from_suffix(path: Path) -> str:
    suffix = path.suffix.casefold()
    if suffix == ".csv":
        return "csv"
    if suffix == ".parquet":
        return "parquet"
    if suffix in {".jsonl", ".ndjson"}:
        return "json_lines"
    if suffix == ".json":
        return "json"
    raise ProjectDataError(f"Unsupported project data file: {path.name}")


def _csv_columns(path: Path) -> tuple[str, ...]:
    try:
        with path.open("r", encoding="utf-8-sig", newline="") as handle:
            sample = handle.read(8192)
            handle.seek(0)
            try:
                dialect = csv.Sniffer().sniff(sample, delimiters=",;\t|")
            except csv.Error:
                dialect = csv.excel
            row = next(csv.reader(handle, dialect), [])
    except (OSError, UnicodeError):
        return ()
    return tuple(str(value).strip() for value in row if str(value).strip())


def _json_columns(path: Path) -> tuple[str, ...]:
    try:
        with path.open("r", encoding="utf-8") as handle:
            if path.suffix.casefold() in {".jsonl", ".ndjson"}:
                first = next((line for line in handle if line.strip()), "")
                value = json.loads(first) if first else {}
            else:
                value = json.load(handle)
        if isinstance(value, list):
            value = next((item for item in value if isinstance(item, dict)), {})
        if isinstance(value, dict):
            return tuple(str(key) for key in value)
    except (OSError, UnicodeError, json.JSONDecodeError):
        return ()
    return ()


def _duckdb_columns(path: Path, source_format: str) -> tuple[str, ...]:
    try:
        import duckdb
    except Exception:
        return ()
    reader = _reader_sql(path, source_format, absolute=True)
    try:
        connection = duckdb.connect(":memory:")
        try:
            rows = connection.execute(f"DESCRIBE SELECT * FROM {reader}").fetchall()
            return tuple(str(row[0]) for row in rows)
        finally:
            connection.close()
    except Exception:
        return ()


def _source_columns(path: Path, source_format: str) -> tuple[str, ...]:
    if source_format == "csv":
        columns = _csv_columns(path)
    elif source_format in {"json", "json_lines"}:
        columns = _json_columns(path)
    else:
        columns = ()
    return columns or _duckdb_columns(path, source_format)


def _infer_primary_key(view: str, columns: Iterable[str]) -> str:
    available = {str(column).casefold(): str(column) for column in columns}
    singular = _singular(view)
    candidates = (
        f"{singular}_id",
        f"{view}_id",
        "id",
    )
    for candidate in candidates:
        if candidate.casefold() in available:
            return available[candidate.casefold()]
    id_columns = [original for key, original in available.items() if key.endswith("_id")]
    return id_columns[0] if len(id_columns) == 1 else ""


def _unique_view(base: str, used: set[str]) -> str:
    candidate = base
    index = 2
    while candidate.casefold() in used:
        candidate = f"{base}_{index}"
        index += 1
    used.add(candidate.casefold())
    return candidate


def discover_sources(project_dir: Path) -> list[ProjectSource]:
    raw_dir = project_dir / "data" / "raw"
    if not raw_dir.is_dir():
        return []
    files = sorted(
        path
        for path in raw_dir.rglob("*")
        if path.is_file()
        and path.suffix.casefold() in SUPPORTED_SUFFIXES
        and not any(part.startswith(".") for part in path.relative_to(raw_dir).parts)
    )
    used: set[str] = set()
    sources: list[ProjectSource] = []
    for path in files:
        view = _unique_view(_slug(path.stem), used)
        source_format = _format_from_suffix(path)
        columns = _source_columns(path, source_format)
        sources.append(
            ProjectSource(
                name=view,
                path=path.relative_to(project_dir).as_posix(),
                format=source_format,
                view=view,
                columns=columns,
                primary_key=_infer_primary_key(view, columns),
            )
        )
    return sources


def infer_relationships(sources: Iterable[ProjectSource]) -> list[ProjectRelationship]:
    source_list = list(sources)
    relationships: list[ProjectRelationship] = []
    seen: set[tuple[str, str, str, str]] = set()
    for parent in source_list:
        if not parent.primary_key:
            continue
        parent_key = parent.primary_key.casefold()
        for child in source_list:
            if child.view == parent.view:
                continue
            match = ""
            for column in child.columns:
                lowered = str(column).casefold()
                if lowered == parent_key or lowered.endswith("_" + parent_key):
                    match = str(column)
                    break
            if not match:
                continue
            key = (parent.view, parent.primary_key, child.view, match)
            if key in seen:
                continue
            seen.add(key)
            relationships.append(
                ProjectRelationship(
                    parent=parent.view,
                    parent_key=parent.primary_key,
                    child=child.view,
                    child_key=match,
                )
            )
    return sorted(
        relationships,
        key=lambda item: (item.parent, item.child, item.child_key),
    )


def _source_dict(source: ProjectSource) -> dict[str, Any]:
    return {
        "name": source.name,
        "path": source.path,
        "format": source.format,
        "view": source.view,
        "primary_key": source.primary_key or None,
        "columns": list(source.columns),
    }


def _relationship_dict(item: ProjectRelationship) -> dict[str, Any]:
    return {
        "parent": item.parent,
        "parent_key": item.parent_key,
        "child": item.child,
        "child_key": item.child_key,
        "cardinality": item.cardinality,
        "inferred": bool(item.inferred),
    }


def _config_payload(plan: ProjectDataPlan) -> dict[str, Any]:
    return {
        "version": CONFIG_VERSION,
        "generated_by": "Data Career Accelerator",
        "generated_at": datetime.now().isoformat(timespec="seconds"),
        "schema": plan.schema,
        "database": DATABASE_RELATIVE.as_posix(),
        "sources": [_source_dict(source) for source in plan.sources],
        "relationships": [_relationship_dict(item) for item in plan.relationships],
    }


def _plan_from_payload(
    root: Path,
    project_id: int,
    project_dir: Path,
    payload: dict[str, Any],
) -> ProjectDataPlan:
    schema = _slug(str(payload.get("schema") or "raw"), "raw")
    sources: list[ProjectSource] = []
    used: set[str] = set()
    for index, raw in enumerate(payload.get("sources") or [], start=1):
        if not isinstance(raw, dict):
            continue
        path_value = str(raw.get("path") or "").strip()
        if not path_value:
            continue
        source_path = _safe_relative(project_dir, path_value)
        if not source_path.is_file():
            continue
        source_format = str(raw.get("format") or _format_from_suffix(source_path)).strip()
        view = _unique_view(
            _slug(str(raw.get("view") or raw.get("name") or source_path.stem), f"table_{index}"),
            used,
        )
        columns = tuple(str(value) for value in (raw.get("columns") or ()))
        if not columns:
            columns = _source_columns(source_path, source_format)
        primary_key = str(raw.get("primary_key") or "").strip()
        if not primary_key:
            primary_key = _infer_primary_key(view, columns)
        sources.append(
            ProjectSource(
                name=str(raw.get("name") or view),
                path=source_path.relative_to(project_dir).as_posix(),
                format=source_format,
                view=view,
                columns=columns,
                primary_key=primary_key,
            )
        )
    relationships: list[ProjectRelationship] = []
    for raw in payload.get("relationships") or []:
        if not isinstance(raw, dict):
            continue
        required = ("parent", "parent_key", "child", "child_key")
        if not all(str(raw.get(key) or "").strip() for key in required):
            continue
        relationships.append(
            ProjectRelationship(
                parent=_slug(str(raw["parent"])),
                parent_key=str(raw["parent_key"]),
                child=_slug(str(raw["child"])),
                child_key=str(raw["child_key"]),
                cardinality=str(raw.get("cardinality") or "one-to-many"),
                inferred=bool(raw.get("inferred", False)),
            )
        )
    if not relationships:
        relationships = infer_relationships(sources)
    database_value = str(payload.get("database") or DATABASE_RELATIVE.as_posix())
    return ProjectDataPlan(
        project_id=int(project_id),
        project_name=PROJECT_NAMES.get(int(project_id), f"Project {int(project_id)}"),
        project_dir=project_dir,
        schema=schema,
        database_path=_safe_relative(project_dir, database_value),
        config_path=project_dir / CONFIG_RELATIVE,
        starter_sql_path=project_dir / STARTER_SQL_RELATIVE,
        findings_path=project_dir / FINDINGS_RELATIVE,
        workspace_path=project_dir / f"{project_dir.name}.code-workspace",
        migration_report_path=project_dir / "documentation" / "portfolio_workspace_migration.md",
        sources=sources,
        relationships=relationships,
    )


def _load_config(root: Path, project_id: int, project_dir: Path) -> ProjectDataPlan | None:
    candidates = [project_dir / CONFIG_RELATIVE]
    candidates.extend(project_dir / relative for relative in LEGACY_CONFIG_RELATIVES)
    path = next((candidate for candidate in candidates if candidate.is_file()), None)
    if path is None:
        return None
    try:
        payload = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    except (OSError, UnicodeError, yaml.YAMLError) as exc:
        raise ProjectDataError(f"Could not read {path.relative_to(project_dir).as_posix()}: {exc}") from exc
    if not isinstance(payload, dict):
        raise ProjectDataError("Project data configuration must be a YAML mapping.")
    plan = _plan_from_payload(root, project_id, project_dir, payload)
    if path != plan.config_path:
        plan.warnings.append(
            f"The source configuration will be moved from {path.relative_to(project_dir).as_posix()} "
            f"to {CONFIG_RELATIVE.as_posix()}."
        )
    return plan

def _new_plan(root: Path, project_id: int, project_dir: Path) -> ProjectDataPlan:
    sources = discover_sources(project_dir)
    plan = ProjectDataPlan(
        project_id=int(project_id),
        project_name=PROJECT_NAMES.get(int(project_id), f"Project {int(project_id)}"),
        project_dir=project_dir,
        schema="raw",
        database_path=project_dir / DATABASE_RELATIVE,
        config_path=project_dir / CONFIG_RELATIVE,
        starter_sql_path=project_dir / STARTER_SQL_RELATIVE,
        findings_path=project_dir / FINDINGS_RELATIVE,
        workspace_path=project_dir / f"{project_dir.name}.code-workspace",
        migration_report_path=project_dir / "documentation" / "portfolio_workspace_migration.md",
        sources=sources,
        relationships=infer_relationships(sources),
    )
    if not sources:
        plan.warnings.append(
            "No CSV, Parquet, JSON, JSONL, or NDJSON files were found under data/raw."
        )
    return plan


def _reader_sql(path: Path, source_format: str, *, absolute: bool = False) -> str:
    value = path.resolve() if absolute else path
    quoted = _sql_string(value)
    if source_format == "csv":
        return f"read_csv_auto({quoted}, header = true)"
    if source_format == "parquet":
        return f"read_parquet({quoted})"
    if source_format == "json_lines":
        return f"read_json_auto({quoted}, format = 'newline_delimited')"
    if source_format == "json":
        return f"read_json_auto({quoted})"
    raise ProjectDataError(f"Unsupported source format: {source_format}")


def setup_sql(plan: ProjectDataPlan, *, absolute_paths: bool = False) -> str:
    """Return the legacy registration script for migration comparisons only."""
    lines = [
        f"-- {MANAGED_HEADER}",
        "-- Re-run this script whenever the raw source files change.",
        f"CREATE SCHEMA IF NOT EXISTS {_qid(plan.schema)};",
        "",
    ]
    for source in plan.sources:
        source_path = _safe_relative(plan.project_dir, source.path)
        path_value = (
            source_path
            if absolute_paths
            else Path("projects") / plan.project_dir.name / source.path
        )
        reader = _reader_sql(path_value, source.format, absolute=absolute_paths)
        lines.extend(
            [
                f"CREATE OR REPLACE VIEW {_qid(plan.schema)}.{_qid(source.view)} AS",
                f"SELECT * FROM {reader};",
                "",
            ]
        )
    if not plan.sources:
        lines.append("-- Add supported source files under data/raw, then refresh this setup.")
    return "\n".join(lines).rstrip() + "\n"


def _legacy_primary_key_sql(plan: ProjectDataPlan) -> str:
    lines = [
        f"-- {MANAGED_HEADER}",
        "-- Each query should return zero rows when the key is unique.",
        "",
    ]
    for source in plan.sources:
        if not source.primary_key:
            continue
        table = f"{_qid(plan.schema)}.{_qid(source.view)}"
        key = _qid(source.primary_key)
        lines.extend(
            [
                f"-- {plan.schema}.{source.view}.{source.primary_key}",
                f"SELECT {key}, COUNT(*) AS row_count",
                f"FROM {table}",
                f"GROUP BY {key}",
                "HAVING COUNT(*) > 1;",
                "",
            ]
        )
    if len(lines) == 3:
        lines.append("-- No primary keys were inferred. Add them to data/project_sources.yaml.")
    return "\n".join(lines).rstrip() + "\n"


def _legacy_orphan_sql(plan: ProjectDataPlan) -> str:
    lines = [
        f"-- {MANAGED_HEADER}",
        "-- Each query should return zero rows when every child key has a parent.",
        "",
    ]
    for item in plan.relationships:
        parent = f"{_qid(plan.schema)}.{_qid(item.parent)}"
        child = f"{_qid(plan.schema)}.{_qid(item.child)}"
        parent_key = _qid(item.parent_key)
        child_key = _qid(item.child_key)
        lines.extend(
            [
                f"-- {item.parent} -> {item.child}",
                f"SELECT c.{child_key} AS missing_parent_key, COUNT(*) AS orphan_rows",
                f"FROM {child} AS c",
                f"LEFT JOIN {parent} AS p",
                f"    ON c.{child_key} = p.{parent_key}",
                f"WHERE c.{child_key} IS NOT NULL",
                f"  AND p.{parent_key} IS NULL",
                f"GROUP BY c.{child_key};",
                "",
            ]
        )
    if len(lines) == 3:
        lines.append("-- No relationships were inferred. Add them to data/project_sources.yaml.")
    return "\n".join(lines).rstrip() + "\n"


def _legacy_cardinality_sql(plan: ProjectDataPlan) -> str:
    lines = [
        f"-- {MANAGED_HEADER}",
        "-- For a valid many-to-one lookup, joined_rows should equal child_rows.",
        "",
    ]
    for item in plan.relationships:
        parent = f"{_qid(plan.schema)}.{_qid(item.parent)}"
        child = f"{_qid(plan.schema)}.{_qid(item.child)}"
        parent_key = _qid(item.parent_key)
        child_key = _qid(item.child_key)
        lines.extend(
            [
                f"-- {item.parent} -> {item.child}",
                "SELECT",
                f"    (SELECT COUNT(*) FROM {child}) AS child_rows,",
                "    COUNT(*) AS joined_rows",
                f"FROM {child} AS c",
                f"LEFT JOIN {parent} AS p",
                f"    ON c.{child_key} = p.{parent_key};",
                "",
            ]
        )
    if len(lines) == 3:
        lines.append("-- No relationships were inferred. Add them to data/project_sources.yaml.")
    return "\n".join(lines).rstrip() + "\n"


def _legacy_consistency_sql(plan: ProjectDataPlan) -> str:
    return (
        f"-- {MANAGED_HEADER}\n"
        "-- Add project-specific checks for duplicated relationship fields.\n"
        "-- Example: compare a child project_id with the project_id on its referenced parent.\n\n"
        "-- Record any cross-table consistency checks below.\n"
    )


def _table_schema_rows(plan: ProjectDataPlan, source: ProjectSource) -> list[tuple[str, str]]:
    if plan.database_path is not None and plan.database_path.is_file():
        try:
            import duckdb

            connection = duckdb.connect(str(plan.database_path), read_only=True)
            try:
                rows = connection.execute(
                    f"DESCRIBE SELECT * FROM {_qid(plan.schema)}.{_qid(source.view)}"
                ).fetchall()
                return [(str(row[0]), str(row[1])) for row in rows]
            finally:
                connection.close()
        except Exception:
            pass
    return [(column, "") for column in source.columns]


def relationship_starter_sql(plan: ProjectDataPlan) -> str:
    """Create a guided but intentionally incomplete learner SQL starter."""
    lines = [
        f"-- {STARTER_HEADER}",
        f"-- Project: {plan.project_name}",
        "--",
        "-- This project database is attached automatically when you open the generated",
        "-- VS Code workspace. Run a statement with Ctrl+Enter, or use the Run CodeLens.",
        "-- Write the real project queries in the TODO sections below.",
        "-- The examples use placeholder names and are not the answers to this task.",
        "",
        "-- ============================================================",
        "-- AVAILABLE TABLES",
        "-- ============================================================",
    ]
    for source in plan.sources:
        lines.append(f"-- {plan.schema}.{source.view}")
        schema_rows = _table_schema_rows(plan, source)
        if schema_rows:
            for column, data_type in schema_rows:
                suffix = f" ({data_type})" if data_type else ""
                key_note = " [primary key candidate]" if column == source.primary_key else ""
                lines.append(f"--   {column}{suffix}{key_note}")
        else:
            lines.append("--   Columns unavailable; refresh the project data workspace.")
        lines.append("")

    lines.extend(
        [
            "-- ============================================================",
            "-- RELATIONSHIPS TO VALIDATE",
            "-- ============================================================",
        ]
    )
    if plan.relationships:
        for item in plan.relationships:
            lines.append(
                f"-- {plan.schema}.{item.child}.{item.child_key} -> "
                f"{plan.schema}.{item.parent}.{item.parent_key}"
            )
    else:
        lines.append("-- Review config/project_sources.yaml and add the relationships for this project.")

    lines.extend(
        [
            "",
            "-- ============================================================",
            "-- 1. CHECK PRIMARY-KEY UNIQUENESS",
            "-- ============================================================",
            "-- Goal: find identifiers that appear more than once.",
            "-- Basic syntax example only:",
            "--",
            "-- SELECT example_id, COUNT(*) AS row_count",
            "-- FROM example_table",
            "-- GROUP BY example_id",
            "-- HAVING COUNT(*) > 1;",
            "--",
            "-- TODO: Write a duplicate-key check for each declared primary key.",
            "",
            "",
            "-- ============================================================",
            "-- 2. CHECK FOR MISSING PARENT RECORDS",
            "-- ============================================================",
            "-- Goal: find child rows whose foreign key has no matching parent.",
            "-- Helpful concepts: LEFT JOIN, matching key columns, and IS NULL.",
            "-- TODO: Write one orphan-key check for each required relationship above.",
            "",
            "",
            "-- ============================================================",
            "-- 3. CHECK JOIN CARDINALITY",
            "-- ============================================================",
            "-- Goal: compare the child row count before and after a many-to-one join.",
            "-- Ask: did the join unexpectedly multiply rows?",
            "-- TODO: Compare row counts for each relationship you plan to use.",
            "",
            "",
            "-- ============================================================",
            "-- 4. ADD PROJECT-SPECIFIC CONSISTENCY CHECKS",
            "-- ============================================================",
            "-- Goal: test business rules that cannot be inferred from column names alone.",
            "-- TODO: Add any cross-table checks required by this project's data model.",
            "",
        ]
    )
    return "\n".join(lines).rstrip() + "\n"


def relationship_findings_markdown(plan: ProjectDataPlan) -> str:
    relationship_rows = []
    for item in plan.relationships:
        relationship_rows.append(
            f"| `{plan.schema}.{item.child}` | `{item.child_key}` | "
            f"`{plan.schema}.{item.parent}` | `{item.parent_key}` | Not tested | |"
        )
    if not relationship_rows:
        relationship_rows.append("|  |  |  |  | Not tested | |")
    return (
        f"<!-- {FINDINGS_HEADER} -->\n"
        f"# {plan.project_name} — Relationship Validation\n\n"
        "Use this document to record what your SQL checks found. Replace the starter "
        "text with your own results and conclusions.\n\n"
        "## Relationships tested\n\n"
        "| Child table | Foreign key | Parent table | Parent key | Result | Notes |\n"
        "|---|---|---|---|---|---|\n"
        + "\n".join(relationship_rows)
        + "\n\n## Duplicate primary keys\n\n"
        "Describe any duplicate identifiers you found, or state that none were returned.\n\n"
        "## Orphaned foreign keys\n\n"
        "Describe child records that did not match a parent record, or state that none were returned.\n\n"
        "## Join cardinality\n\n"
        "Record whether each join preserved the expected child-row count.\n\n"
        "## Exceptions and decisions\n\n"
        "Document intentional exceptions, source-data problems, and any cleanup decisions.\n\n"
        "## Final conclusion\n\n"
        "State whether the tested relationships are safe to use for analysis and what must be fixed first.\n"
    )


def workspace_payload(plan: ProjectDataPlan) -> dict[str, Any]:
    database_relative = DATABASE_RELATIVE.as_posix()
    return {
        "dcaManaged": True,
        "folders": [{"name": plan.project_name, "path": "."}],
        "settings": {
            "files.associations": {"*.sql": "sql"},
            "duckdb.databases": [
                {
                    "alias": "project",
                    "type": "file",
                    "path": f"./{database_relative}",
                    "readOnly": False,
                    "attached": True,
                }
            ],
            "duckdb.defaultDatabase": "project",
            "duckdb.resultsLocation": "beside",
        },
    }


def _write_workspace(plan: ProjectDataPlan) -> None:
    if plan.workspace_path is None:
        return
    path = plan.workspace_path
    if path.exists():
        try:
            existing = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, UnicodeError, json.JSONDecodeError):
            existing = None
        if isinstance(existing, dict) and not existing.get("dcaManaged"):
            path = path.with_name(path.stem + "-dca.code-workspace")
            plan.workspace_path = path
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(workspace_payload(plan), indent=2) + "\n", encoding="utf-8")


def _write_once(path: Path | None, content: str) -> None:
    if path is None or path.exists():
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def _same_text(left: str, right: str) -> bool:
    return left.replace("\r\n", "\n").strip() == right.replace("\r\n", "\n").strip()


def _archive_path(plan: ProjectDataPlan, source: Path) -> Path:
    stamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    try:
        relative = source.relative_to(plan.project_dir)
    except ValueError:
        relative = Path(source.name)
    return plan.project_dir / "archive" / "portfolio-workspace-migration" / stamp / relative


def _record_migration(plan: ProjectDataPlan, actions: list[str]) -> None:
    if not actions or plan.migration_report_path is None:
        return
    path = plan.migration_report_path
    path.parent.mkdir(parents=True, exist_ok=True)
    heading = "# Portfolio SQL Workspace Migration\n\n"
    if not path.exists():
        path.write_text(heading, encoding="utf-8")
    with path.open("a", encoding="utf-8") as handle:
        handle.write(f"## {datetime.now().isoformat(timespec='seconds')}\n\n")
        for action in actions:
            handle.write(f"- {action}\n")
        handle.write("\n")


def _remove_or_archive_legacy(plan: ProjectDataPlan) -> list[str]:
    actions: list[str] = []
    expected = {
        LEGACY_SETUP_RELATIVES[0]: setup_sql(plan),
        LEGACY_SETUP_RELATIVES[1]: setup_sql(plan),
        LEGACY_VALIDATION_RELATIVES[0]: _legacy_primary_key_sql(plan),
        LEGACY_VALIDATION_RELATIVES[1]: _legacy_orphan_sql(plan),
        LEGACY_VALIDATION_RELATIVES[2]: _legacy_cardinality_sql(plan),
        LEGACY_VALIDATION_RELATIVES[3]: _legacy_consistency_sql(plan),
    }
    for relative, generated in expected.items():
        path = plan.project_dir / relative
        if not path.is_file():
            continue
        try:
            current = path.read_text(encoding="utf-8")
        except (OSError, UnicodeError):
            continue
        if _same_text(current, generated):
            path.unlink()
            actions.append(f"Deleted outdated generated file `{relative.as_posix()}`.")
        elif MANAGED_HEADER in current:
            archive = _archive_path(plan, path)
            archive.parent.mkdir(parents=True, exist_ok=True)
            shutil.move(str(path), str(archive))
            actions.append(
                f"Archived edited legacy file `{relative.as_posix()}` to "
                f"`{archive.relative_to(plan.project_dir).as_posix()}`."
            )
    setup_dir = plan.project_dir / "sql" / "setup"
    try:
        if setup_dir.is_dir() and not any(setup_dir.iterdir()):
            setup_dir.rmdir()
            actions.append("Removed the empty legacy `sql/setup/` folder.")
    except OSError:
        pass
    return actions


def _migrate_config(plan: ProjectDataPlan) -> list[str]:
    actions: list[str] = []
    if plan.config_path is None:
        return actions
    plan.config_path.parent.mkdir(parents=True, exist_ok=True)
    for relative in LEGACY_CONFIG_RELATIVES:
        old = plan.project_dir / relative
        if not old.is_file():
            continue
        if not plan.config_path.exists():
            shutil.move(str(old), str(plan.config_path))
            actions.append(
                f"Moved source configuration to `{CONFIG_RELATIVE.as_posix()}`."
            )
        else:
            try:
                same = _same_text(
                    old.read_text(encoding="utf-8"),
                    plan.config_path.read_text(encoding="utf-8"),
                )
            except (OSError, UnicodeError):
                same = False
            if same:
                old.unlink()
                actions.append(f"Deleted duplicate legacy configuration `{relative.as_posix()}`.")
            else:
                archive = _archive_path(plan, old)
                archive.parent.mkdir(parents=True, exist_ok=True)
                shutil.move(str(old), str(archive))
                actions.append(
                    f"Archived legacy configuration to `{archive.relative_to(plan.project_dir).as_posix()}`."
                )
    return actions


def write_generated_files(plan: ProjectDataPlan, *, refresh: bool = False) -> None:
    if plan.config_path is None:
        raise ProjectDataError("Project data plan is missing its source configuration path.")
    actions = _migrate_config(plan)
    plan.config_path.parent.mkdir(parents=True, exist_ok=True)
    if refresh or not plan.config_path.exists():
        plan.config_path.write_text(
            yaml.safe_dump(_config_payload(plan), sort_keys=False, allow_unicode=True),
            encoding="utf-8",
        )
    _write_workspace(plan)
    _write_once(plan.starter_sql_path, relationship_starter_sql(plan))
    _write_once(plan.findings_path, relationship_findings_markdown(plan))
    actions.extend(_remove_or_archive_legacy(plan))
    _record_migration(plan, actions)

def build_database(plan: ProjectDataPlan) -> bool:
    if plan.database_path is None:
        return False
    if not plan.sources:
        plan.warnings.append("The project database was not built because no sources were found.")
        return False
    try:
        import duckdb
    except Exception:
        plan.warnings.append("DuckDB is not installed, so the project database was not built.")
        return False
    plan.database_path.parent.mkdir(parents=True, exist_ok=True)
    try:
        connection = duckdb.connect(str(plan.database_path))
        try:
            connection.execute(f"CREATE SCHEMA IF NOT EXISTS {_qid(plan.schema)}")
            for source in plan.sources:
                source_path = _safe_relative(plan.project_dir, source.path)
                reader = _reader_sql(source_path, source.format, absolute=True)
                connection.execute(
                    f"CREATE OR REPLACE VIEW {_qid(plan.schema)}.{_qid(source.view)} "
                    f"AS SELECT * FROM {reader}"
                )
        finally:
            connection.close()
    except Exception as exc:
        plan.warnings.append(f"Could not build the project DuckDB workspace: {exc}")
        return False
    plan.database_ready = plan.database_path.is_file()
    return plan.database_ready


def _refresh_discovered_sources(plan: ProjectDataPlan) -> None:
    discovered = discover_sources(plan.project_dir)
    existing_by_path = {source.path.casefold(): source for source in plan.sources}
    merged: list[ProjectSource] = []
    used: set[str] = set()
    for item in discovered:
        previous = existing_by_path.get(item.path.casefold())
        if previous is None:
            view = _unique_view(item.view, used)
            merged.append(
                ProjectSource(
                    name=item.name,
                    path=item.path,
                    format=item.format,
                    view=view,
                    columns=item.columns,
                    primary_key=item.primary_key,
                )
            )
            continue
        view = _unique_view(previous.view, used)
        merged.append(
            ProjectSource(
                name=previous.name,
                path=item.path,
                format=item.format,
                view=view,
                columns=item.columns,
                primary_key=previous.primary_key or item.primary_key,
            )
        )
    plan.sources = merged
    valid_views = {source.view for source in merged}
    preserved = [
        relationship
        for relationship in plan.relationships
        if relationship.parent in valid_views and relationship.child in valid_views
    ]
    seen = {
        (item.parent, item.parent_key, item.child, item.child_key)
        for item in preserved
    }
    for item in infer_relationships(merged):
        key = (item.parent, item.parent_key, item.child, item.child_key)
        if key not in seen:
            preserved.append(item)
            seen.add(key)
    plan.relationships = sorted(
        preserved,
        key=lambda item: (item.parent, item.child, item.child_key),
    )


def prepare_project_data_workspace(
    root: Path,
    project_id: int,
    *,
    refresh: bool = False,
    build: bool = True,
) -> ProjectDataPlan:
    root = Path(root).resolve()
    project_dir = _project_dir(root, int(project_id))
    if not project_dir.is_dir():
        raise ProjectDataError(f"Project folder does not exist: {project_dir}")
    plan = _load_config(root, int(project_id), project_dir)
    if plan is None:
        plan = _new_plan(root, int(project_id), project_dir)
    elif refresh:
        _refresh_discovered_sources(plan)
    if build:
        build_database(plan)
    elif plan.database_path is not None:
        plan.database_ready = plan.database_path.is_file()
    write_generated_files(plan, refresh=refresh)
    return plan

def _repo_relative(root: Path, path: Path | None) -> str:
    if path is None:
        return ""
    try:
        return path.resolve().relative_to(Path(root).resolve()).as_posix()
    except ValueError:
        return str(path)


def guide_managed_block(root: Path, plan: ProjectDataPlan) -> str:
    source_lines = []
    schema_sections = []
    for source in plan.sources:
        schema_rows = _table_schema_rows(plan, source)
        source_lines.append(
            f"| `{source.path}` | `{plan.schema}.{source.view}` | "
            f"`{source.primary_key or 'Review required'}` | {len(schema_rows) or 'Unknown'} |"
        )
        detail = [
            f"### `{plan.schema}.{source.view}`",
            "",
            "| Column | Data type |",
            "|---|---|",
        ]
        if schema_rows:
            for column, data_type in schema_rows:
                detail.append(f"| `{column}` | `{data_type or 'Unknown'}` |")
        else:
            detail.append("| _Schema unavailable_ |  |")
        schema_sections.append("\n".join(detail))
    if not source_lines:
        source_lines.append("| _No supported files found under `data/raw`_ |  |  |  |")

    relationship_lines = []
    for item in plan.relationships:
        relationship_lines.append(
            f"| `{plan.schema}.{item.child}` | `{item.child_key}` | "
            f"`{plan.schema}.{item.parent}` | `{item.parent_key}` | {item.cardinality} |"
        )
    if not relationship_lines:
        relationship_lines.append(
            "| _No relationships inferred_ |  |  |  | Review the project source configuration |"
        )

    status = (
        "Ready — open the starter in VS Code and run SQL with the DuckDB extension."
        if plan.database_ready
        else "The project database could not be prepared. Review the warning below."
    )
    warning_text = ""
    if plan.warnings:
        warning_text = "\n\n> " + "\n> ".join(plan.warnings)

    return (
        f"{MANAGED_GUIDE_START}\n"
        "## Your SQL workspace is ready\n\n"
        "The app prepares this project's DuckDB database in the background. You do not "
        "need to register CSV files, run setup SQL, or calculate file paths before starting.\n\n"
        f"- Starter SQL: `{_repo_relative(root, plan.starter_sql_path)}`\n"
        f"- Findings document: `{_repo_relative(root, plan.findings_path)}`\n"
        f"- Project database: `{_repo_relative(root, plan.database_path)}`\n"
        f"- VS Code workspace: `{_repo_relative(root, plan.workspace_path)}`\n"
        f"- Source configuration: `{_repo_relative(root, plan.config_path)}`\n"
        f"- Status: **{status}**{warning_text}\n\n"
        "Click **Open Starter in VS Code**. The generated workspace automatically attaches "
        "the project database as `project` and selects it as the active DuckDB database. "
        "Use **Ctrl+Enter** to run SQL or the **Run** link above an individual statement.\n\n"
        "### Available tables\n\n"
        "| Raw source | SQL table | Primary-key candidate | Columns |\n"
        "|---|---|---|---:|\n"
        + "\n".join(source_lines)
        + "\n\n### Table schemas\n\n"
        + "\n\n".join(schema_sections)
        + "\n\n### Relationships to validate\n\n"
        "These relationships are inferred from matching ID columns. Confirm them against "
        "the project documentation before treating them as business rules.\n\n"
        "| Child table | Foreign key | Parent table | Parent key | Expected relationship |\n"
        "|---|---|---|---|---|\n"
        + "\n".join(relationship_lines)
        + f"\n{MANAGED_GUIDE_END}"
    )


def relationship_guide_markdown(root: Path, plan: ProjectDataPlan, label: str) -> str:
    return (
        f"# {plan.project_name} — Validate Table Relationships\n\n"
        f"**Milestone:** {label}\n\n"
        "## What this task means\n\n"
        "Before using joins in your analysis, confirm that the tables connect the way you "
        "expect. A query can run successfully and still produce incorrect totals when IDs "
        "are duplicated, child records point to missing parents, or a join multiplies rows.\n\n"
        f"{guide_managed_block(root, plan)}\n\n"
        "## How to complete the task\n\n"
        "### 1. Open the starter SQL\n\n"
        "Click **Open Starter in VS Code**. The file contains the actual table schemas, "
        "relationship list, short syntax reminders, and blank TODO areas. It intentionally "
        "does not contain the finished project queries.\n\n"
        "### 2. Check primary-key uniqueness\n\n"
        "For every table with a declared primary key, group by that identifier and count "
        "how many rows use it. Keep only identifiers whose count is greater than one.\n\n"
        "A basic pattern looks like this, using placeholder names:\n\n"
        "```sql\n"
        "SELECT example_id, COUNT(*) AS row_count\n"
        "FROM example_table\n"
        "GROUP BY example_id\n"
        "HAVING COUNT(*) > 1;\n"
        "```\n\n"
        "Write the real checks yourself using the project tables listed above.\n\n"
        "### 3. Check for orphaned foreign keys\n\n"
        "For each child-to-parent relationship, use a `LEFT JOIN` to keep every child row. "
        "Then identify child rows where the corresponding parent key is missing. The starter "
        "names the relationships but leaves the join SQL for you to write.\n\n"
        "### 4. Check join cardinality\n\n"
        "Count the child table before the join and compare it with the joined result. A "
        "many-to-one lookup should normally preserve the child-row count. If the count grows, "
        "investigate duplicate parent keys or an incomplete join condition.\n\n"
        "### 5. Record what you found\n\n"
        "Open the findings document and record duplicate IDs, orphaned records, row-count "
        "changes, exceptions, and your final conclusion about whether each relationship is safe.\n\n"
        "## Definition of done\n\n"
        "- [ ] The project database opened successfully in the generated VS Code workspace.\n"
        "- [ ] Every declared primary-key candidate was checked for duplicates.\n"
        "- [ ] Every required relationship was checked for missing parent records.\n"
        "- [ ] Join row counts were compared for the relationships used in the analysis.\n"
        "- [ ] Project-specific consistency checks were added where needed.\n"
        "- [ ] The findings document contains results, exceptions, and a final conclusion.\n"
    )


def _carried_forward_notes(content: str) -> str:
    notes: list[str] = []
    for line in str(content or "").splitlines():
        stripped = line.strip()
        if re.match(r"^- \[[xX]\]", stripped):
            notes.append(stripped)
        elif stripped.startswith("|") and "Yes / No" not in stripped:
            cells = [cell.strip() for cell in stripped.strip("|").split("|")]
            if cells and not all(not cell or set(cell) <= {"-", ":"} for cell in cells):
                if any(cell and cell not in {"Relationship", "Parent duplicates", "Orphan children", "Child rows", "Joined rows", "Safe to use?", "Resolution"} for cell in cells):
                    if any(cell for cell in cells if cell not in {"", "Yes / No"}):
                        notes.append(stripped)
    return "\n".join(dict.fromkeys(notes))


def upgrade_relationship_guide(root: Path, plan: ProjectDataPlan, content: str) -> str:
    text = str(content or "")
    fresh = relationship_guide_markdown(root, plan, "Validate relationships")
    if not text.strip():
        return fresh
    if MANAGED_GUIDE_START in text and (
        "Step 1 — Review the generated source configuration" in text
        or "Run `sql/validation/01_primary_key_checks.sql`" in text
        or "Portable setup SQL" in text
    ):
        carried = _carried_forward_notes(text)
        if carried:
            fresh += (
                "\n\n## Notes carried forward from the previous guide\n\n"
                "Review these entries and move confirmed results into the new findings document.\n\n"
                + carried
                + "\n"
            )
        return fresh

    managed = guide_managed_block(root, plan)
    if MANAGED_GUIDE_START in text and MANAGED_GUIDE_END in text:
        pattern = re.compile(
            re.escape(MANAGED_GUIDE_START) + r".*?" + re.escape(MANAGED_GUIDE_END),
            flags=re.S,
        )
        return pattern.sub(managed, text, count=1)

    insertion = text.find("\n## ")
    if insertion >= 0:
        next_heading = text.find("\n## ", insertion + 1)
        position = next_heading if next_heading >= 0 else len(text)
        return text[:position] + "\n\n" + managed + text[position:]
    return text.rstrip() + "\n\n" + managed + "\n"


def _vscode_command() -> str | None:
    for command in ("code", "code.cmd"):
        found = shutil.which(command)
        if found:
            return found
    if os.name == "nt":
        candidates = []
        local = os.environ.get("LOCALAPPDATA")
        program_files = os.environ.get("ProgramFiles")
        program_files_x86 = os.environ.get("ProgramFiles(x86)")
        if local:
            candidates.extend(
                [
                    Path(local) / "Programs" / "Microsoft VS Code" / "bin" / "code.cmd",
                    Path(local) / "Programs" / "Microsoft VS Code Insiders" / "bin" / "code-insiders.cmd",
                ]
            )
        for base in (program_files, program_files_x86):
            if base:
                candidates.extend(
                    [
                        Path(base) / "Microsoft VS Code" / "bin" / "code.cmd",
                        Path(base) / "Microsoft VS Code Insiders" / "bin" / "code-insiders.cmd",
                    ]
                )
        for candidate in candidates:
            if candidate.is_file():
                return str(candidate)
    return None


def open_starter_in_vscode(plan: ProjectDataPlan) -> str:
    if not plan.database_ready or plan.database_path is None or not plan.database_path.is_file():
        raise ProjectDataError("The project database is not ready. Refresh the project data first.")
    if plan.starter_sql_path is None or not plan.starter_sql_path.is_file():
        raise ProjectDataError("The SQL starter file is missing. Refresh the project data first.")
    if plan.workspace_path is None or not plan.workspace_path.is_file():
        raise ProjectDataError("The VS Code workspace is missing. Refresh the project data first.")
    command = _vscode_command()
    if command:
        subprocess.Popen(
            [command, "-r", str(plan.workspace_path), "-g", str(plan.starter_sql_path)],
            cwd=str(plan.project_dir),
        )
        return "VS Code"
    if os.name == "nt":
        os.startfile(str(plan.workspace_path))
        os.startfile(str(plan.starter_sql_path))
        return "VS Code or the default editor"
    if sys.platform == "darwin":
        subprocess.Popen(["open", "-a", "Visual Studio Code", str(plan.workspace_path)])
        subprocess.Popen(["open", str(plan.starter_sql_path)])
        return "VS Code"
    raise ProjectDataError(
        "VS Code could not be found. Open the generated .code-workspace file manually, "
        f"then open {plan.starter_sql_path}."
    )


def plan_summary(plan: ProjectDataPlan) -> str:
    status = "ready for VS Code" if plan.database_ready else "needs attention"
    return (
        f"{plan.source_count} source{'s' if plan.source_count != 1 else ''} • "
        f"{plan.relationship_count} relationship candidate"
        f"{'s' if plan.relationship_count != 1 else ''} • {status}"
    )
